# GET ALL USERS
GET http://localhost:5000/users/
###


# GET A SINGLE USER
GET http://localhost:5000/users/0
###

# REGISTER A USER
POST http://localhost:5000/register
content-type: application/json

{
       "email":"poo@lookatthat.com",
       "password":"1234567891011"
}
###

# SIGN IN
POST http://localhost:5000/login
content-type: application/json

{
       "email":"me@lookatthat.com",
       "password":"12345678910"
}


###

# GET ALL BOOKINGS
GET http://localhost:5000/booking
###

# GET ALL BOOKINGS FOR A USER
GET http://localhost:5000/users/0/booking
###


http://localhost:5000/listing

###


#GET  http://localhost:5000/users HTTP/1.1
content-type: application/json

###

http://localhost:5000/booking

###


http://localhost:5000/listing/

###


#POST http://localhost:5000/users HTTP/1.1
#content-type: application/json

#{
#       "title": "new", "views": 30 
#    
# }